{% set name = "somajo" %}
{% set version = "2.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/SoMaJo-{{ version }}.tar.gz
  sha256: fa38a2804e6e811f03f9eb1dac56d42b6ccdf1bd316445f5c20f18a93fab4d48

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - regex >=2019.02.18

test:
  imports:
    - somajo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/tsproisl/SoMaJo
  summary: A tokenizer and sentence splitter for German and English web and social media texts.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - iulusoy
