{% set name = "somajo" %}
{% set version = "2.4.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 848fcf6107bf10dec918cc16d8c40944b844757c2ed724b01a87ff391f68e6f7

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - regex >=2019.02.18

test:
  imports:
    - somajo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tsproisl/SoMaJo
  summary: A tokenizer and sentence splitter for German and English web and social media texts.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - iulusoy
