{% set name = "somajo" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: baa6d8442e5e299ea3d81b8cdf6d3d14d86ff4aa3c89236a1c4b18692f31ff90

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - regex >=2019.02.18

test:
  imports:
    - somajo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/tsproisl/SoMaJo
  summary: A tokenizer and sentence splitter for German and English web and social media texts.
  license: GPL-3.0-or-later
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - iulusoy
